### ISSUE TITLE
OTA with a single slot?

### ISSUE THREAD

**Issue by jobidon** [SmingHub/SmingRTOS#111]
I am trying to determine if it would be possible to implement a single-slot OTA. I would like to use rBoot with a single ROM slot and the code would d/l an update to flash, directly over the current one. That doesn't work. I tried moving the ota_callback routine to RAM with IRAM_ATTR to avoid messing up the callback during the transfer, but it doesn't seem to help. Is there a different way to do this?

I can think of 2 workarounds:
- create a small 2nd slot and populate it with a small OTA routine to do the upgrade. Boot from it, and then revert to the other ROM afterwards.
- an HTTP download of the new ROM which could then be copied to flash at the correct location

thoughts?

**Comment by hreintke** [comment]
- Using the same location for the updated application doesn't work as the application and sdk code is executed from flash.
- A "small" second slot is a possibility but beware that really small is not possible. The majority of the size is taken by sdk code, only little for application code. Probably you will end up with two close to identical sizes.
- Don't know what you want to achieve with the http download. If there is enough room in the spifss to download the updated application, there is also enough room to flash it directly to the right location.
- What is the spi_size of your esp ?

**Comment by jobidon** [comment]
I'm using an ESP-12 with the 4MB flash, but the problem stems from the 
fact that I need a full 3MB for the spiffs. I guess I could alternate 
between a 1MB/3MB partition to the inverse, a 3MB/1MB layout and 
download the new ROM to the spiffs, reboot to it, and download the new 
spiffs at the new location afterwards.

**Comment by hreintke** [comment]
@jobidon : 
Not sure what you mean with 
- the 3MB/1MB layout. An application can never exceed 1MB due to the architecture of the the esp. 
- Download the new rom to spiffs. An Application (ROM) cannot be downloaded to the spiffs and then started. The spiffs area has a filesystem layout, a ROM has an "application layout" and they are very different. Using OTA is directly writing to flash. 
  Main question is : What is the size of your application.
  If that is less than 500MB, you can just OTA with two applications. A small boot only application will be around 250MB, leaving around 750MB for yours. 
  If that doesn't fit, Options are 1/ unmount spiffs, 2/ OTA application, 3/ Switch 4/ format & mount spiffs 5/ upload spiffs

**Comment by raburton** [comment]
I think I see what you mean. You could use 1mb rom + 3 mb spiffs, then when you want to ota unmount the spiffs, write the new rom to the last mb (corrupting the existing spiffs) and put the new spiffs in the first 3mb of flash (excluding the first 2 sectors). You wouldn't be able to update the spiffs at the same time as the rom though, you'd have to reboot to the new rom first and then download the new spiffs, so you wouldn't have the new spiffs available on that reboot or if anything goes wrong and you have to revert back to the first rom it's spiffs wouldn't be usable. As @hreintke says maybe you can fit both your roms in the first 1mb?

**Comment by hreintke** [comment]
Issue solved
