### ISSUE TITLE
rboot & rboot-api into sming instead of application

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#19]
Richard,
Not because of the basic_rboot trouble that we had/have but..

I think it is better to move the compiling of both rboot and rboot/appcode from application to smingframework.

Both have the same characteristics as the framework : no need to update on a per-application base.
Framework build would then generate : 
- libsming which includes rboot/appcode
- rboot.bin
  
  By doing this we would : 
- Get a clear distinction between application and framework
- Limit the risk that application compile fails due to "framework compiles"
- We can combine makefile-project and makefile-rboot and remove the redundancy in that

**Comment by raburton** [comment]
rBoot compilation has per project options, so it cannot be built along with libsming. App code also has these per project options so cannot be included in libsming. Makefile-rboot.mk does more than just add the extra module, it would be possible to combine these into a single file, but it would be horribly complex, I know because this is what I tried first.
