### ISSUE TITLE
esp_systemapi 

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#5]
@raburton : 
In your "libsming PR" you commented out the lines below 
//extern void *pvPortMalloc(size_t xWantedSize, const char *file, uint32 line);
//extern void vPortFree(void *ptr, const char *file, uint32 line);

In my dev environment that prevents rboot-api.c to compile. 
For that I need them to be in.

Any specific reason for you to get the out ?

**Comment by raburton** [comment]
I got a duplicate definition warning, they were being defined somewhere else (as I'm not at home now I can't check, but I think it was from the sdk). Aren't these the same ones we had to remove from regular Sming to support sdk v1.4.0, because they were now defined in that sdk include files?

**Comment by raburton** [comment]
I notice that rboot-integration.h isn't in the rtos version, that would pull in extra headers. What version of the Sming source did you base this port on?

**Comment by raburton** [comment]
Not sure why it works on mine and not on yours though. Somehow mine must be pulling in another header from the sdk that yours isn't. I can't see why that would be though.

**Comment by hreintke** [comment]
I did not work on/see detailed updates in the SDK1.4.0 patch, but checking now there were updates/location moves on these files.

I.ll check in that area.

On rboot : Noticed testerday that I wrongly used my rboot-bios branch when starting rtos conversion.
Works without changes to applications but should be reverted.
Will do that today. 

But in the same direction on your remark. I presume you use the code from my repo so should get same results.

**Comment by raburton** [comment]
Yes, I checked it out from here, so should work the same! Assuming we are using the same sdk of course. Oh, worth noting my sdk is unmodified. Your original instructions said to copy various bits from the repo to the sdk, but that's no longer needed as I've got all the includes and lib folders set up now as part of the build. Might be worth reverting to a clean sdk.

**Comment by raburton** [comment]
Keeping this in sync with upstream is likely to be a a pain!

**Comment by hreintke** [comment]
Thanks, good hint on the issue. 
And completely agree on not updating sdk. 
Did not know how to do that when initially working on the conversion so took a shortcut for the time being.

When you updated saw the simple solution.

**Comment by hreintke** [comment]
Did not yet found the reason for the missing/duplicate functions.
//extern void *pvPortMalloc(size_t xWantedSize, const char *file, uint32 line);
//extern void vPortFree(void *ptr, const char *file, uint32 line);

Now used the RTOS_SDK from UDK_209 and also the one from Espressif Github.
Same results.

if it's easy to do : When getting a duplicate definition warning I thing the output from the compiler identifies both locations. Can you see/check what came out of that at your side ?

Will continue investigation.

**Comment by hreintke** [comment]
BTW : Forgot to ask, from where did you get the RTOS_SDK

**Comment by raburton** [comment]
Got back from long days at work / couple of days away and had a look at this. Now that I'm not viewing it on my phone I noticed you said the problem was in compiling rboot-api.c I haven't tried compiling this in rtos yet, the only app I've used is your test one that I moved over to a new rtos sample project. I tried porting Basic_rboot over to rtos this morning before work, but it wasn't that simple. rBoot itself doesn't build with rtos for a start. Now rBoot doesn't really require the sdk, but it does use the linker file from the sdk to know where to call the rom functions on the device. The rtos linker file doesn't contain SPIRead or similar functions anymore. There are similarly named functions but these do not point to the same rom code address, which is odd. They can't have changed the addresses, so these are obviously not the same functions. This needs to be looked into further, but not something I could do in half an hour before work this morning. Anyway, if you have rBoot compiled with the normal SDK it should still work fine and I'll look into getting it building (might have to go back to shipping a linker script with rBoot again). Then I can work out what's up with the rboot-api.

**Comment by raburton** [comment]
Oh, and my rtos sdk came straight from github.

**Comment by hreintke** [comment]
I did not realize that the rboot base was not yet included. Wanted to get all compiling in the makefile and missed this. I did include rboot-api so at the moment that is being compiled when building sming lib.

Include the rboot directory now as module. Hit a rboot-hex2a.h not found error.
I only see this file in the out directory. Is that being build somewhere in the process ?

On SpiRead. Sming does use SPIRead for accessing Spiffs files, and that works as expected. So functional it looks OK.
What  noticed is : 
When having the SPI_SIZE (or map in the UDK makefile) to small (I used 512k instead of 4M). I got reading errors outside the range of 512K. When updating to correct flash size, it worked correctly.
Did not test/used that in the NONOS version so don't know whether it is RTOS SDK specific.
Do you want me to test that ?

Rboot-api compiles OK when uncommnting the extern ... lines in esp_systemapi.h. 
I see these functions also defined in the freertos portable.h file.
Will also work further on this.

**Comment by raburton** [comment]
Spiffs doesn't use SPIRead, it uses an SDK function.
rboot-hex2a.h is created with esptool2 as part of the rBoot build process.
Hope to get a little more time at the weekend, but I have a case presentation to do for next week and I have really neglected my portfolio so I need to spend some time doing real work unfortunately too.

**Comment by hreintke** [comment]
Ai, I should have known the SPIRead. I asked you a question about it and you explained.
Of course no problem of having less/no time for Sming.

I will keep you informed on my progress.

**Comment by raburton** [comment]
No problem. I had a little look this morning and it appears that they haven't done anything too odd (like change the address of functions in the rom - not possible after release, or you'd have two different versions of esp8266 to have to target). The reason the functions look like they have different address is that they are calling deeper into the code, they seem to be skipping a layer of code that does some locking +/- other stuff. I don't know what the api for these calls is, so it's probably easier to keep targeting the higher level functions. But as the two sdks provide different functions in their linker scripts I'll just have to add a linker script to rBoot, instead of using the one in the sdk since it isn't common.

**Comment by raburton** [comment]
Found the conflict. rtos sdk includes some spiffs code, that was was including a freertos header file that contained a define. Blocked the rtos spiffs, for the moment at least.

**Comment by hreintke** [comment]
Nice catch. 
I read (not test) that RTOS SDK include full spiffs.
Checked that but it doesn't use the "Magic" setting we discussed earlier.
